### ISSUE TITLE
R CMD check --as-cran

### ISSUE THREAD

**Issue by markvanderloo** [data-cleaning/validatetools#7]
Gives:

```
Conversion of ‘README.md’ failed:
pandoc: Could not fetch http://www.r-pkg.org/badges/version/validatetools
TlsExceptionHostPort (HandshakeFailed Error_EOF) "www.r-pkg.org" 80
Non-standard file/directory found at top level:
```
We either need `.Rbuildignore` (meh) or use a more sensible non-devtools directory structure :-).

**Comment by edwindj** [comment]
Fixed by adding "README.md" to ".Rbuildignore".

Whether non-devtools is more sensible is up for debate :-), I prefer to stay as mainstream as possible, and right now that is devtools (rstudio provides good support for it).
